/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedPracticeRouteImport } from './routes/_authenticated/practice'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedMockRouteImport } from './routes/_authenticated/mock'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedSessionPreviewRouteImport } from './routes/_authenticated/session.preview'
import { Route as AuthenticatedPracticePart2SpeakRouteImport } from './routes/_authenticated/practice.part-2.speak'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPracticeRoute = AuthenticatedPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMockRoute = AuthenticatedMockRouteImport.update({
  id: '/mock',
  path: '/mock',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSessionPreviewRoute =
  AuthenticatedSessionPreviewRouteImport.update({
    id: '/session/preview',
    path: '/session/preview',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPracticePart2SpeakRoute =
  AuthenticatedPracticePart2SpeakRouteImport.update({
    id: '/part-2/speak',
    path: '/part-2/speak',
    getParentRoute: () => AuthenticatedPracticeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/home': typeof AuthenticatedHomeRoute
  '/mock': typeof AuthenticatedMockRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/practice': typeof AuthenticatedPracticeRouteWithChildren
  '/progress': typeof AuthenticatedProgressRoute
  '/session/preview': typeof AuthenticatedSessionPreviewRoute
  '/practice/part-2/speak': typeof AuthenticatedPracticePart2SpeakRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/home': typeof AuthenticatedHomeRoute
  '/mock': typeof AuthenticatedMockRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/practice': typeof AuthenticatedPracticeRouteWithChildren
  '/progress': typeof AuthenticatedProgressRoute
  '/session/preview': typeof AuthenticatedSessionPreviewRoute
  '/practice/part-2/speak': typeof AuthenticatedPracticePart2SpeakRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/mock': typeof AuthenticatedMockRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/practice': typeof AuthenticatedPracticeRouteWithChildren
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/_authenticated/session/preview': typeof AuthenticatedSessionPreviewRoute
  '/_authenticated/practice/part-2/speak': typeof AuthenticatedPracticePart2SpeakRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/home'
    | '/mock'
    | '/onboarding'
    | '/practice'
    | '/progress'
    | '/session/preview'
    | '/practice/part-2/speak'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/home'
    | '/mock'
    | '/onboarding'
    | '/practice'
    | '/progress'
    | '/session/preview'
    | '/practice/part-2/speak'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/home'
    | '/_authenticated/mock'
    | '/_authenticated/onboarding'
    | '/_authenticated/practice'
    | '/_authenticated/progress'
    | '/_authenticated/session/preview'
    | '/_authenticated/practice/part-2/speak'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/practice': {
      id: '/_authenticated/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof AuthenticatedPracticeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mock': {
      id: '/_authenticated/mock'
      path: '/mock'
      fullPath: '/mock'
      preLoaderRoute: typeof AuthenticatedMockRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/session/preview': {
      id: '/_authenticated/session/preview'
      path: '/session/preview'
      fullPath: '/session/preview'
      preLoaderRoute: typeof AuthenticatedSessionPreviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/practice/part-2/speak': {
      id: '/_authenticated/practice/part-2/speak'
      path: '/part-2/speak'
      fullPath: '/practice/part-2/speak'
      preLoaderRoute: typeof AuthenticatedPracticePart2SpeakRouteImport
      parentRoute: typeof AuthenticatedPracticeRoute
    }
  }
}

interface AuthenticatedPracticeRouteChildren {
  AuthenticatedPracticePart2SpeakRoute: typeof AuthenticatedPracticePart2SpeakRoute
}

const AuthenticatedPracticeRouteChildren: AuthenticatedPracticeRouteChildren = {
  AuthenticatedPracticePart2SpeakRoute: AuthenticatedPracticePart2SpeakRoute,
}

const AuthenticatedPracticeRouteWithChildren =
  AuthenticatedPracticeRoute._addFileChildren(
    AuthenticatedPracticeRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedMockRoute: typeof AuthenticatedMockRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPracticeRoute: typeof AuthenticatedPracticeRouteWithChildren
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedSessionPreviewRoute: typeof AuthenticatedSessionPreviewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedMockRoute: AuthenticatedMockRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPracticeRoute: AuthenticatedPracticeRouteWithChildren,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedSessionPreviewRoute: AuthenticatedSessionPreviewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
